from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

from decision_index_constants import (
    GUARD_FAMILY_ORDER,
    INDEXES_DIR,
    MECHANIC_PARENT_ORDER,
    MEMORY_OBJECT_CLASS_ORDER,
    SURFACE_CLASS_ORDER,
)
from decision_index_records import DecisionRecord


def ordered_values(values: Iterable[str], preferred_order: Sequence[str]) -> list[str]:
    seen = set(values)
    ordered = [value for value in preferred_order if value in seen]
    ordered.extend(sorted(seen - set(ordered)))
    return ordered


def render_generated_notice() -> str:
    return "<!-- Generated by scripts/root-topology/build_decision_indexes.py; do not edit by hand. -->\n\n"


def display_title(record: DecisionRecord) -> str:
    if record.title.startswith(record.decision_id):
        return record.title
    return f"{record.decision_id} {record.title}"


def bullet_line(record: DecisionRecord) -> str:
    return f"- [{display_title(record)}]({record.index_link}) (`{record.repo_path}`)"


def render_indexes_readme() -> str:
    return (
        "# Decision Lookup Indexes\n\n"
        + render_generated_notice()
        + "These files are generated read models from decision-note `Decision ID` and `Index Metadata`.\n"
        + "Decision notes own rationale; these indexes only make lookup cheaper for agents.\n\n"
        + "## Indexes\n\n"
        + "- [By canonical ID and number](by-number.md)\n"
        + "- [By date](by-date.md)\n"
        + "- [By surface class](by-surface.md)\n"
        + "- [By mechanic parent](by-mechanic.md)\n"
        + "- [By validation or guard family](by-guard.md)\n"
        + "- [By memory-object class](by-memory-object-class.md)\n"
    )


def render_by_number(records: Sequence[DecisionRecord]) -> str:
    lines = [
        "# Decisions By Canonical ID And Number",
        "",
        render_generated_notice().rstrip(),
        "",
        "| ID | Date | Decision | Canonical path | Surface classes | Mechanic parents | Guard families | Memory object classes | Posture |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for record in records:
        lines.append(
            "| {id} | {date} | [{title}]({link}) | `{path}` | {surfaces} | {parents} | {guards} | {classes} | {posture} |".format(
                id=record.decision_id,
                date=record.date,
                title=display_title(record),
                link=record.index_link,
                path=record.repo_path,
                surfaces=", ".join(record.surface_classes) or "none",
                parents=", ".join(record.mechanic_parents) or "none",
                guards=", ".join(record.guard_families) or "none",
                classes=", ".join(record.memory_object_classes) or "none",
                posture=record.posture,
            )
        )
    return "\n".join(lines) + "\n"


def render_grouped_index(
    *,
    title: str,
    records: Sequence[DecisionRecord],
    attribute: str,
    preferred_order: Sequence[str],
) -> str:
    values: list[str] = []
    for record in records:
        values.extend(getattr(record, attribute))
    lines = ["# " + title, "", render_generated_notice().rstrip(), ""]
    for value in ordered_values(values, preferred_order):
        lines.extend([f"## {value}", ""])
        for record in records:
            if value in getattr(record, attribute):
                lines.append(bullet_line(record))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_by_date(records: Sequence[DecisionRecord]) -> str:
    lines = ["# Decisions By Date", "", render_generated_notice().rstrip(), ""]
    for date in ordered_values((record.date for record in records), ()):
        lines.extend([f"## {date}", ""])
        for record in records:
            if record.date == date:
                lines.append(bullet_line(record))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index_files(records: Sequence[DecisionRecord]) -> dict[Path, str]:
    return {
        INDEXES_DIR / "README.md": render_indexes_readme(),
        INDEXES_DIR / "by-number.md": render_by_number(records),
        INDEXES_DIR / "by-date.md": render_by_date(records),
        INDEXES_DIR / "by-surface.md": render_grouped_index(
            title="Decisions By Surface Class",
            records=records,
            attribute="surface_classes",
            preferred_order=SURFACE_CLASS_ORDER,
        ),
        INDEXES_DIR / "by-mechanic.md": render_grouped_index(
            title="Decisions By Mechanic Parent",
            records=records,
            attribute="mechanic_parents",
            preferred_order=MECHANIC_PARENT_ORDER,
        ),
        INDEXES_DIR / "by-guard.md": render_grouped_index(
            title="Decisions By Validation Or Guard Family",
            records=records,
            attribute="guard_families",
            preferred_order=GUARD_FAMILY_ORDER,
        ),
        INDEXES_DIR / "by-memory-object-class.md": render_grouped_index(
            title="Decisions By Memory-Object Class",
            records=records,
            attribute="memory_object_classes",
            preferred_order=MEMORY_OBJECT_CLASS_ORDER,
        ),
    }
